-- Estrutura DEZE7. As tabelas do Immagine não são alteradas.
create extension if not exists pgcrypto;

create table if not exists public.deze7_products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text not null default '',
  category text not null check (category in ('camiseta','kit','acessorio')),
  price numeric(10,2) not null check (price >= 0),
  cost numeric(10,2) check (cost is null or cost >= 0),
  image_url text,
  active boolean not null default true,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deze7_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.deze7_products(id) on delete cascade,
  sku text not null unique,
  size text,
  color text,
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(product_id,size,color)
);

create table if not exists public.deze7_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.deze7_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  status text not null default 'novo' check (status in ('novo','confirmado','pago','separacao','enviado','concluido','cancelado')),
  subtotal numeric(10,2) not null default 0 check (subtotal >= 0),
  shipping numeric(10,2) not null default 0 check (shipping >= 0),
  total numeric(10,2) not null default 0 check (total >= 0),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deze7_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.deze7_orders(id) on delete cascade,
  product_id uuid not null references public.deze7_products(id),
  variant_id uuid references public.deze7_variants(id),
  product_name text not null,
  variant_label text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  line_total numeric(10,2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists deze7_variants_product_id_idx on public.deze7_variants(product_id);
create index if not exists deze7_orders_created_at_idx on public.deze7_orders(created_at desc);
create index if not exists deze7_orders_status_idx on public.deze7_orders(status);
create index if not exists deze7_order_items_order_id_idx on public.deze7_order_items(order_id);
create index if not exists deze7_order_items_product_id_idx on public.deze7_order_items(product_id);
create index if not exists deze7_order_items_variant_id_idx on public.deze7_order_items(variant_id);

alter table public.deze7_products enable row level security;
alter table public.deze7_variants enable row level security;
alter table public.deze7_admins enable row level security;
alter table public.deze7_orders enable row level security;
alter table public.deze7_order_items enable row level security;
